from pathlib import Path
from typing import List, Dict, Any, Tuple
from rich.console import Console

from app.adaptors.django_adaptor import DjangoAdapter
from app.adaptors.base import BaseAdapter, SchemaEventData
from cli.client import APIClient

console = Console()


def detect_framework(path: Path) -> BaseAdapter | None:
    """
    Auto-detect migration framework.

    Currently supports:
    - Django

    Future support:
    - Alembic
    - SQLAlchemy
    - Rails
    """
    adapters = [
        DjangoAdapter(),
        # TODO: AlembicAdapter(), etc.
    ]

    for adapter in adapters:
        if adapter.detect(path):
            return adapter

    return None


def scan_migrations(
    path: Path,
    project_id: int,
    client: APIClient,
    framework: str = "auto"
) -> Tuple[List[Dict[str, Any]], int]:
    """
    Scan migration files and prepare events for upload.

    Returns:
        - List of events (ready for bulk upload)
        - Number of models created
    """

    if framework == "auto":
        console.print("Auto-detecting framework...")
        adapter = detect_framework(path)
        if not adapter:
            raise ValueError(
                f"Could not detect migration framework in {path}. "
                "Try specifying --framework django"
            )
        console.print(f"[green]✓[/green] Detected: {adapter.get_framework_name()}")
    else:
        if framework == "django":
            adapter = DjangoAdapter()
        else:
            raise ValueError(f"Unknown framework: {framework}")

    console.print(f"Parsing migration files...")
    events_data: List[SchemaEventData] = adapter.parse(path)

    if not events_data:
        console.print("[yellow]Warning: No events extracted from migrations[/yellow]")
        console.print("[dim]This could mean:[/dim]")
        console.print("  - No migration files found")
        console.print("  - Django adapter parser not fully implemented")
        console.print("  - Migrations contain no tracked operations")
        return [], 0

    console.print(f"[green]✓[/green] Found {len(events_data)} events")

    model_names = set(event.model_name for event in events_data)
    console.print(f"[green]✓[/green] Found {len(model_names)} unique models")

    console.print("Creating models...")
    model_name_to_id = {}
    models_created = 0

    for model_name in sorted(model_names):
        try:
            # Try to find existing model
            models = client.list_models(project_id=project_id)
            existing = next((m for m in models if m['name'] == model_name), None)

            if existing:
                model_name_to_id[model_name] = existing['id']
                console.print(f"  [dim]Using existing model: {model_name}[/dim]")
            else:
                model = client.create_model(
                    project_id=project_id,
                    name=model_name,
                    description=f"Auto-created from migration scan"
                )
                model_name_to_id[model_name] = model['id']
                models_created += 1
                console.print(f"  [green]✓[/green] Created model: {model_name}")

        except Exception as e:
            console.print(f"  [yellow]Warning: Could not create model {model_name}: {e}[/yellow]")
            continue

    api_events = []
    skipped = 0

    for event in events_data:
        model_id = model_name_to_id.get(event.model_name)
        if not model_id:
            console.print(f"  [yellow]Warning: Skipping event for unknown model {event.model_name}[/yellow]")
            skipped += 1
            continue

        api_events.append({
            "model_id": model_id,
            "event_type": event.event_type,
            "field_name": event.field_name,
            "risk_level": event.risk_level,
            "metadata": event.metadata
            # timestamp is auto-generated by database
        })

    if skipped > 0:
        console.print(f"[yellow]Skipped {skipped} events due to missing models[/yellow]")

    return api_events, models_created
