# Generated by Django 4.2 on 2024-01-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_add_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='email',
            field=models.EmailField(max_length=320, unique=True),
        ),
        migrations.RemoveField(
            model_name='User',
            name='bio',
        ),
        migrations.RenameField(
            model_name='User',
            old_name='created_at',
            new_name='date_joined',
        ),
    ]
